# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Load Balancer Nodes
  LoadBalancerCount = 2

  (1..LoadBalancerCount).each do |i|

    config.vm.define "loadbalancer#{i}" do |lb|

      lb.vm.box               = "bento/ubuntu-22.04"
      lb.vm.box_check_update  = false
      #lb.vm.box_version       = "3.3.0"
      lb.vm.hostname          = "loadbalancer#{i}.example.com"

      lb.vm.network "private_network", ip: "172.16.16.5#{i}"

      lb.vm.provider :virtualbox do |v|
        v.name   = "loadbalancer#{i}"
        v.memory = 1024
        v.cpus   = 1
        #Goup Cluster VM
        v.customize ["modifyvm", :id, "--groups", "/HA-Kubenetes-Cluster-External-Keepalived"]
      end

      lb.vm.provider :virtualbox do |v|
        v.memory  = 1024
        v.cpus    = 1
        #Goup Cluster VM
        v.customize ["modifyvm", :id, "--groups", "/HA-Kubenetes-Cluster-External-Keepalived"]
      end

    end

  end


  # Kubernetes Master Nodes
  MasterCount = 3

  (1..MasterCount).each do |i|

    config.vm.define "kmaster#{i}" do |masternode|

      masternode.vm.box               = "bento/ubuntu-22.04"
      masternode.vm.box_check_update  = false
      #masternode.vm.box_version       = "3.3.0"
      masternode.vm.hostname          = "kmaster#{i}.example.com"

      masternode.vm.network "private_network", ip: "172.16.16.10#{i}"

      masternode.vm.provider :virtualbox do |v|
        v.name   = "kmaster#{i}"
        v.memory = 3072
        v.cpus   = 2
        #Goup Cluster VM
        v.customize ["modifyvm", :id, "--groups", "/HA-Kubenetes-Cluster-External-Keepalived"]
      end
    
      masternode.vm.provider :virtualbox do |v|
        #v.nested  = true
        v.memory  = 3072
        v.cpus    = 2
        #Goup Cluster VM
        v.customize ["modifyvm", :id, "--groups", "/HA-Kubenetes-Cluster-External-Keepalived"]
      end

    end

  end


  # Kubernetes Worker Nodes
  WorkerCount = 1

  (1..WorkerCount).each do |i|

    config.vm.define "kworker#{i}" do |workernode|

      workernode.vm.box               = "bento/ubuntu-22.04"
      workernode.vm.box_check_update  = false
      #workernode.vm.box_version       = "3.3.0"
      workernode.vm.hostname          = "kworker#{i}.example.com"

      workernode.vm.network "private_network", ip: "172.16.16.20#{i}"

      workernode.vm.provider :virtualbox do |v|
        v.name   = "kworker#{i}"
        v.memory = 3072
        v.cpus   = 2
        #Goup Cluster VM
        v.customize ["modifyvm", :id, "--groups", "/HA-Kubenetes-Cluster-External-Keepalived"]
      end

      workernode.vm.provider :virtualbox do |v|
        #v.nested  = true
        v.memory  = 3072
        v.cpus    = 2
        #Goup Cluster VM
        v.customize ["modifyvm", :id, "--groups", "/HA-Kubenetes-Cluster-External-Keepalived"]
      end

    end

  end


  # Kubernetes Worker Nodes
  ClusterAdminCount = 1

  (1..ClusterAdminCount).each do |i|

    config.vm.define "cluster-admin#{i}" do |clusteradmin|

      clusteradmin.vm.box               = "bento/ubuntu-22.04"
      clusteradmin.vm.box_check_update  = false
      #adminhost.vm.box_version       = "3.3.0"
      clusteradmin.vm.hostname          = "cluster-admin#{i}.example.com"

      clusteradmin.vm.network "private_network", ip: "172.16.16.3#{i}"

      clusteradmin.vm.provider :virtualbox do |v|
        v.name   = "cluster-admin#{i}"
        v.memory = 1024
        v.cpus   = 1
        #Goup Cluster VM
        v.customize ["modifyvm", :id, "--groups", "/HA-Kubenetes-Cluster-External-Keepalived"]
      end

      clusteradmin.vm.provider :virtualbox do |v|
        #v.nested  = true
        v.memory  = 1024
        v.cpus    = 1
        #Goup Cluster VM
        v.customize ["modifyvm", :id, "--groups", "/HA-Kubenetes-Cluster-External-Keepalived"]
      end

    end

  end

end